# Generated by Django 2.2.19 on 2023-09-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя персонжажа')),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('species', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless'), ('unknown', 'Unknown')], default='unknown', max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя локации')),
                ('type', models.CharField(max_length=255)),
                ('dimension', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя локации')),
                ('air_date', models.CharField(max_length=255)),
                ('episode', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('characters', models.ManyToManyField(related_name='episodes', to='locations.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_origin', to='locations.Location'),
        ),
    ]
